version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.2
jobs:
  unit-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test
      - codecov/upload:
          file: coverage/coverage-final.json
          conf: codecov.yml
      - store_artifacts:
          path: coverage

workflows:
  test-flow:
    jobs:
      - unit-test
